Remove unused unserializable state
Fixes the following error when opening the TranscriptDetailsWidget:
DataCloneError: Failed to execute 'put' on 'IDBObjectStore': [object
Object] could not be cloned.